version: '3'

services:
  rabbitmq:
    image: rabbitmq:3.7.8-alpine
    container_name: rabbitmq_prato
    hostname: rabbitmq_prato
    volumes:
    - ./rabbitmq:/var/lib/rabbitmq

  bot_webhook:
    build: .
    command: python webhooks.py
    ports:
    - 5001:5001
    volumes:
    - .:/code

  worker:
    build: .
    command: celery -A chat_processor  worker --loglevel=info
    volumes:
    - .:/code
    links:
    - rabbitmq
    depends_on:
    - rabbitmq

networks:
  default:
    external:
      name: pratoaberto